language: node_js
node_js: 6

env:
  global:
    secure: Kqj1HCy8U4etUaohmPM1fy8UQhx821iRmklOQuD+EbORErogoRQc9d8e2mVQsb5Pi9feYjgwh4LlsRh/BCGZN1f6bDql0PyRjYqPyr2Asts1DbMWZx0LZKSn37QSI8PS+M63FnqP7hRYl0ZdL0rBYH0rwvhE/uTwA8ZOi/4qd9rypIafx62QT8DowdynQbPEc11Ad7E7zpNER70xIem8XA9s1+B3/b+qWvWZXWogKUwZg0XPJRBALovApDmsjTkfNLodMe3vTwQ/WvfMxJSaW0drRUsYS6GBDHCRQXEUOLbDT5wCqNZHZtTZScpsRyqT9XDAZc4sKbeXWUaa6IX14GPwVZ7tJQ5ES74hr7ULQtG4ONQfsWuj/nMRJK3oHpFwiFEf1wr1OrzpwkRPpR8X2YmrwrOu25IFCgADyO01CKiHdCUOZy9obLscUcSNIhl6YmO2nd588qnWcw4Jj+Iv7ZXyPDP83ar/wpul9lEMpX9HVHZrZEdVjWSpXaBuGpF6dE1LJ1UJKUroTRt4Wt/ic8BleAb8dVy+ArzBPIx9vH5b3r/krQ5RIf8rr4etSzDtRjJdvN9OmxaMwl7tXRlR/vOo51AoQSdiWvV4k36ygaAXDsDNBafaLligwkBI181uft57nJEpYUPVfFSdhFXeI+5vt3Mke/W3WizlzxSFr/0=

deploy:
  skip_cleanup: true
  provider: script
  script: "./resources/publish.sh"
  on:
    branch: zh-cn